defaultNamespace: cattle-monitoring-system
# Custom helm options
helm:
  releaseName: prometheus-federator
  chart: prometheus-federator
  repo: https://charts.rancher.io
  version: 1.0.0+up0.1.1
  values:
    global:
      cattle:
        url: https://rancher.giebert.eu
    helmProjectOperator:
      helmController:
        enabled: false
      helmLocker:
        enabled: false 
      releaseRoleBindings:
        clusterRoleRefs:
          admin: admin
          edit: edit
          view: view

dependsOn:
  - name: dgiebert-fleet-rancher-monitoring

# https://github.com/rancher/fleet/issues/633
# Needs Target Customization per Cluster
targetCustomizations:
- name: init
  helm:
    values:
      global:
        cattle:
          clusterId: c-m-np2kjb4x
          systemProjectId: p-zbm6q
  yaml:
    overlays:
    - p-zbm6q
  clusterSelector:
    matchLabels:
      management.cattle.io/cluster-name: c-m-np2kjb4x